Configure ECS deployment w/ github actions
mbta/draft pull request #8
Opened 2021-05-17 16:47 UTC by KaylaBrady

[Ticket](https://app.asana.com/0/1199969637453355/1200247733385052)

This PR adds the ECS deployment GHA and adds a Dockerfile to specify how to build a Draft image. Referenced [arrow's Dockerfile](https://github.com/mbta/arrow/blob/master/Dockerfile) for this. I noticed Skate's `.dockerignore` additionally ignores everything from `priv` that isn't in `!/priv/repo/migrations` -- is that a pattern we'd want to follow as well, or is it standard for everything in `priv` is included in the image?

2021-05-17 16:49 UTC, KaylaBrady commented on .github/workflows/deploy-ecs.yml
> +          docker-repo: ${{ secrets.DOCKER_REPO }}
Are these secrets (+ SLACK_WEBHOOK) already setup for Draft? Can I be added as an admin of this repo, or is that permission restricted?

2021-05-18 13:57 UTC, paulswartz requested changes

2021-05-18 13:57 UTC, paulswartz commented on .github/workflows/deploy-ecs.yml
> +          docker-repo: ${{ secrets.DOCKER_REPO }}
SLACK_WEBHOOK is already set up (it's global to all MBTA projects).
I added tje AWS keys earlier, and DOCKER_REPO today.

2021-05-18 13:57 UTC, paulswartz commented on config/Dockerfile
> +FROM hexpm/elixir:1.11.4-erlang-23.3-debian-buster-20210208 as builder
I believe the build script is looking for `Dockerfile` to live at the top-level.

2021-05-18 13:57 UTC, paulswartz commented on config/Dockerfile
> +RUN  curl -sL https://deb.nodesource.com/setup_14.x | bash - \
We're trying to migrate applications to install Node as part of a multi-stage build. Ian has an example for the parking repo: https://github.com/mbta/parking_lpr/blob/idw-ecs-deploy/Dockerfile

2021-05-18 13:57 UTC, paulswartz commented on config/.dockerignore
> +_build
I believe the build script is looking for this to live at the top-level.

2021-05-18 15:28 UTC, KaylaBrady commented on config/Dockerfile
> +RUN  curl -sL https://deb.nodesource.com/setup_14.x | bash - \
Oh cool, I've updated following that example!

2021-05-18 17:26 UTC, ianwestcott commented on Dockerfile
> +COPY --from=app-builder /root/_build/prod/rel/screens .
I suspect this path is incorrect since it references `screens`

2021-05-18 17:46 UTC, paulswartz commented on Dockerfile
> +COPY --from=app-builder /root/_build/prod/rel/screens .
👍 @KaylaBrady you can test out the build locally w/ `docker build .`: it should get to the end successfully.

2021-05-18 19:05 UTC, KaylaBrady commented on Dockerfile
> +  libssl1.1 libsctp1 curl \
True -- now that curl isn't needed for installing node it can be removed!

2021-05-18 19:08 UTC, KaylaBrady commented on Dockerfile
> +COPY --from=app-builder /root/_build/prod/rel/screens .
🤦‍♀️ Thanks for catching! I've now tested locally with docker build & docker run w/ my local DB configuration for environment variables and confirmed there were no errors logged.

2021-05-18 19:33 UTC, paulswartz approved these changes
🍰

2021-05-19 13:03 UTC, merged